export const tickers: { [key: string]: string } = {
	bitcoin: 'btc',
	ethereum: 'eth',
	binance: 'bnb',
	cardano: 'ada',
	solana: 'sol',
	fantom: 'ftm',
	cosmos: 'atom',
	thorchain: 'rune',
	internet_computer: 'icp',
	polkadot: 'dox',
	avalanche: 'avax',
	tron: 'trx',
	near: 'near',
	stellar: 'xlm',
	algorand: 'algo',
	flow: 'flow',
	eos: 'eos',
	hedera: 'hbar',
	tezoz: 'xtz',
	elrond: 'egld',
	polygon: 'matic',
};
