export const tickers = {
	bitcoin: 'btc',
	ethereum: 'eth',
	binance: 'bnb',
	cardano: 'ada',
	solana: 'sol',
	fantom: 'ftm',
	cosmos: 'atom',
	thorchain: 'rune',
	'internet computer': 'icp',
	polkadot: 'dox',
	avalanche: 'avax',
	tron: 'trx',
	near: 'near',
	'stellar lumens': 'xlm',
	algorand: 'algo',
	flow: 'flow',
	eos: 'eos',
	'hedera hashbar': 'hbar',
	quant: 'qnt',
	tezoz: 'xtz',
	elrond: 'egld',
	polygon: 'matic',
};
